name: 'Pterodactyl-Restart'
description: 'Automatically restart a pterodactyl container on commit'
author: '[Supercrafter100]'

inputs:
  PTE_PANEL_URL:
    description: 'The pterodactyl panel URL'
    required: true
  
  PTE_BEARER_TOKEN:
    description: 'the bearer token for the panel to authorize'
    required: true
  
  PTE_PANEL_ID:
    description: 'The ID of that panel that has to be restarted'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'